#include <stdio.h>
#include <string.h>
#include "gui.h"

static AppData app;

/* GTK3 dialog content areas are GtkBox containers, so store the grid directly. */
static GtkWidget *dialog_grid_lookup(GtkWidget *content_area) {
    return GTK_WIDGET(g_object_get_data(G_OBJECT(content_area), "dialog-grid"));
}
#undef GTK_BIN
#define GTK_BIN(widget) GTK_WIDGET(widget)
#define gtk_bin_get_child(widget) dialog_grid_lookup(GTK_WIDGET(widget))

void append_text_output(GtkTextBuffer *b, const char *text) { GtkTextIter end; gtk_text_buffer_get_end_iter(b, &end); gtk_text_buffer_insert(b, &end, text, -1); gtk_text_buffer_insert(b, &end, "\n", -1); }
void clear_text_output(GtkTextBuffer *b) { gtk_text_buffer_set_text(b, "", -1); }
static GtkWidget *output_view(GtkTextBuffer **b) { *b=gtk_text_buffer_new(NULL); GtkWidget *v=gtk_text_view_new_with_buffer(*b),*s=gtk_scrolled_window_new(NULL,NULL); gtk_text_view_set_editable(GTK_TEXT_VIEW(v),FALSE); gtk_text_view_set_monospace(GTK_TEXT_VIEW(v),TRUE); gtk_container_add(GTK_CONTAINER(s),v); return s; }
static void add_column(GtkWidget *view,const char *name,int col){GtkCellRenderer *r=gtk_cell_renderer_text_new();GtkTreeViewColumn *c=gtk_tree_view_column_new_with_attributes(name,r,"text",col,NULL);gtk_tree_view_append_column(GTK_TREE_VIEW(view),c);}
static void grid_row(GtkWidget *grid,int row,const char *label,GtkWidget *field){GtkWidget *l=gtk_label_new(label);gtk_widget_set_halign(l,GTK_ALIGN_END);gtk_grid_attach(GTK_GRID(grid),l,0,row,1,1);gtk_grid_attach(GTK_GRID(grid),field,1,row,1,1);}
static GtkWidget *dialog_grid(const char *title){GtkWidget *d=gtk_dialog_new_with_buttons(title,GTK_WINDOW(app.window),GTK_DIALOG_MODAL,"Cancel",GTK_RESPONSE_CANCEL,"OK",GTK_RESPONSE_OK,NULL),*g=gtk_grid_new(),*scroll=gtk_scrolled_window_new(NULL,NULL),*content=gtk_dialog_get_content_area(GTK_DIALOG(d));gtk_grid_set_row_spacing(GTK_GRID(g),6);gtk_grid_set_column_spacing(GTK_GRID(g),8);gtk_container_set_border_width(GTK_CONTAINER(g),12);gtk_scrolled_window_set_policy(GTK_SCROLLED_WINDOW(scroll),GTK_POLICY_NEVER,GTK_POLICY_AUTOMATIC);gtk_widget_set_hexpand(scroll,TRUE);gtk_widget_set_vexpand(scroll,TRUE);gtk_widget_set_size_request(scroll,560,420);gtk_window_set_default_size(GTK_WINDOW(d),620,520);gtk_container_add(GTK_CONTAINER(scroll),g);gtk_container_add(GTK_CONTAINER(content),scroll);g_object_set_data(G_OBJECT(content),"dialog-grid",g);return d;}
static void refresh_processes(void){gtk_list_store_clear(app.sched_list_store);for(int i=0;i<app.num_processes;i++){Process *p=&app.processes[i];GtkTreeIter it;gtk_list_store_append(app.sched_list_store,&it);gtk_list_store_set(app.sched_list_store,&it,0,p->name,1,p->arrival_time,2,p->burst_time,3,p->priority,4,p->completion_time,5,p->waiting_time,6,p->turnaround_time,-1);}}
static void refresh_memory(void){gtk_list_store_clear(app.storage_list_store);for(int i=0;i<app.num_blocks;i++){MemoryBlock *b=&app.storage_blocks[i];GtkTreeIter it;gtk_list_store_append(app.storage_list_store,&it);gtk_list_store_set(app.storage_list_store,&it,0,b->block_id,1,b->size,2,b->is_allocated?"ALLOCATED":"FREE",3,b->process_name,-1);}}
static int memory_name_exists(const char *name){for(int i=0;i<app.num_blocks;i++)if(app.storage_blocks[i].is_allocated&&!strcmp(app.storage_blocks[i].process_name,name))return 1;return 0;}

static void log_submit(const char *message){append_text_output(app.sched_output_buffer,message);append_text_output(app.banker_output_buffer,message);append_text_output(app.storage_output_buffer,message);}
static void on_submit_job(GtkButton *button,gpointer unused){(void)button;(void)unused;GtkWidget *d=dialog_grid("Submit Job"),*g=gtk_bin_get_child(GTK_BIN(gtk_dialog_get_content_area(GTK_DIALOG(d))));GtkWidget *name=gtk_entry_new(),*arrival=gtk_spin_button_new_with_range(0,10000,1),*burst=gtk_spin_button_new_with_range(1,10000,1),*priority=gtk_spin_button_new_with_range(0,999,1),*size=gtk_spin_button_new_with_range(1,100000,1),*strategy=gtk_combo_box_text_new();gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(strategy),"First Fit");gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(strategy),"Best Fit");gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(strategy),"Worst Fit");gtk_combo_box_set_active(GTK_COMBO_BOX(strategy),0);grid_row(g,0,"Job name:",name);grid_row(g,1,"Arrival time:",arrival);grid_row(g,2,"CPU burst:",burst);grid_row(g,3,"Priority:",priority);grid_row(g,4,"Memory KB:",size);grid_row(g,5,"Memory strategy:",strategy);GtkWidget *claim[MAX_RESOURCES],*request[MAX_RESOURCES];for(int r=0;r<MAX_RESOURCES;r++){claim[r]=gtk_spin_button_new_with_range(0,100000,1);request[r]=gtk_spin_button_new_with_range(0,100000,1);char a[32],b[32];snprintf(a,sizeof a,"R%d max claim:",r);snprintf(b,sizeof b,"R%d request:",r);grid_row(g,6+r*2,a,claim[r]);grid_row(g,7+r*2,b,request[r]);}gtk_widget_show_all(d);if(gtk_dialog_run(GTK_DIALOG(d))==GTK_RESPONSE_OK){Job j;memset(&j,0,sizeof j);snprintf(j.name,sizeof j.name,"%s",gtk_entry_get_text(GTK_ENTRY(name)));j.arrival_time=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(arrival));j.cpu_burst=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(burst));j.priority=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(priority));j.memory_size=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(size));for(int r=0;r<MAX_RESOURCES;r++){j.claim[r]=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(claim[r]));j.request[r]=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(request[r]));}char msg[256];submit_job(&app.jobs,&app.banker_system,app.storage_blocks,app.num_blocks,app.processes,&app.num_processes,&j,(AllocationStrategy)gtk_combo_box_get_active(GTK_COMBO_BOX(strategy)),msg,sizeof msg);log_submit(msg);refresh_processes();refresh_memory();}gtk_widget_destroy(d);}
static void on_complete_job(GtkButton *button,gpointer unused){(void)button;(void)unused;GtkWidget *d=dialog_grid("Complete Job"),*g=gtk_bin_get_child(GTK_BIN(gtk_dialog_get_content_area(GTK_DIALOG(d)))),*name=gtk_entry_new();grid_row(g,0,"Job name:",name);gtk_widget_show_all(d);if(gtk_dialog_run(GTK_DIALOG(d))==GTK_RESPONSE_OK){char msg[256];complete_job(&app.jobs,&app.banker_system,app.storage_blocks,app.num_blocks,app.processes,&app.num_processes,gtk_entry_get_text(GTK_ENTRY(name)),msg,sizeof msg);log_submit(msg);refresh_processes();refresh_memory();}gtk_widget_destroy(d);}
static void on_run_schedule(GtkButton *b,gpointer u){(void)b;(void)u;if(!app.num_processes){append_text_output(app.sched_output_buffer,"No granted jobs are waiting for CPU scheduling.");return;}GtkWidget *d=dialog_grid("Run Scheduling"),*g=gtk_bin_get_child(GTK_BIN(gtk_dialog_get_content_area(GTK_DIALOG(d)))),*combo=gtk_combo_box_text_new();const char *names[]={"FCFS","SJF","Round Robin","Priority"};for(int i=0;i<4;i++)gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(combo),names[i]);gtk_combo_box_set_active(GTK_COMBO_BOX(combo),0);grid_row(g,0,"Algorithm:",combo);gtk_widget_show_all(d);if(gtk_dialog_run(GTK_DIALOG(d))==GTK_RESPONSE_OK){int a=gtk_combo_box_get_active(GTK_COMBO_BOX(combo));if(a==FCFS)schedule_fcfs(app.processes,app.num_processes);else if(a==SJF)schedule_sjf(app.processes,app.num_processes);else if(a==ROUND_ROBIN)schedule_round_robin(app.processes,app.num_processes,gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(app.sched_quantum_spin)));else schedule_priority(app.processes,app.num_processes);copy_schedule_metrics(&app.jobs,app.processes,app.num_processes);refresh_processes();char msg[100];snprintf(msg,sizeof msg,"%s completed for %d active job(s).",names[a],app.num_processes);clear_text_output(app.sched_output_buffer);append_text_output(app.sched_output_buffer,msg);}gtk_widget_destroy(d);}
static GtkWidget *create_scheduling_tab(void){GtkWidget *box=gtk_box_new(GTK_ORIENTATION_VERTICAL,8),*view;gtk_container_set_border_width(GTK_CONTAINER(box),10);app.sched_list_store=gtk_list_store_new(7,G_TYPE_STRING,G_TYPE_INT,G_TYPE_INT,G_TYPE_INT,G_TYPE_INT,G_TYPE_INT,G_TYPE_INT);view=gtk_tree_view_new_with_model(GTK_TREE_MODEL(app.sched_list_store));const char *cols[]={"Job","Arrival","Burst","Priority","Complete","Waiting","Turnaround"};for(int i=0;i<7;i++)add_column(view,cols[i],i);GtkWidget *s=gtk_scrolled_window_new(NULL,NULL);gtk_container_add(GTK_CONTAINER(s),view);gtk_widget_set_vexpand(s,TRUE);gtk_box_pack_start(GTK_BOX(box),s,TRUE,TRUE,0);GtkWidget *c=gtk_box_new(GTK_ORIENTATION_HORIZONTAL,8),*submit=gtk_button_new_with_label("Submit Job"),*complete=gtk_button_new_with_label("Complete Job"),*run=gtk_button_new_with_label("Run Schedule");app.sched_quantum_spin=gtk_spin_button_new_with_range(1,100,1);gtk_spin_button_set_value(GTK_SPIN_BUTTON(app.sched_quantum_spin),2);g_signal_connect(submit,"clicked",G_CALLBACK(on_submit_job),NULL);g_signal_connect(complete,"clicked",G_CALLBACK(on_complete_job),NULL);g_signal_connect(run,"clicked",G_CALLBACK(on_run_schedule),NULL);gtk_box_pack_start(GTK_BOX(c),submit,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(c),complete,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(c),run,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(c),gtk_label_new("RR quantum:"),FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(c),app.sched_quantum_spin,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(box),c,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(box),output_view(&app.sched_output_buffer),TRUE,TRUE,0);return box;}

static void on_init_banker(GtkButton *b,gpointer u){(void)b;(void)u;GtkWidget *d=dialog_grid("Initialize Banker Resources"),*g=gtk_bin_get_child(GTK_BIN(gtk_dialog_get_content_area(GTK_DIALOG(d))));GtkWidget *capacity[MAX_RESOURCES];for(int r=0;r<MAX_RESOURCES;r++){capacity[r]=gtk_spin_button_new_with_range(0,100000,1);char label[32];snprintf(label,sizeof label,"R%d available:",r);grid_row(g,r,label,capacity[r]);}gtk_widget_show_all(d);if(gtk_dialog_run(GTK_DIALOG(d))==GTK_RESPONSE_OK){init_banker_system(&app.banker_system,MAX_CLIENTS,MAX_RESOURCES);for(int r=0;r<MAX_RESOURCES;r++)app.banker_system.available[r]=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(capacity[r]));app.banker_initialized=1;clear_text_output(app.banker_output_buffer);append_text_output(app.banker_output_buffer,"Banker system initialized for 10 resource types.");append_text_output(app.banker_output_buffer,get_banker_state_string(&app.banker_system));}gtk_widget_destroy(d);}
static void on_banker_request(GtkButton *b,gpointer u){(void)b;(void)u;if(!app.banker_initialized){append_text_output(app.banker_output_buffer,"Initialize the Banker system first.");return;}GtkWidget *d=dialog_grid("Resource Request"),*g=gtk_bin_get_child(GTK_BIN(gtk_dialog_get_content_area(GTK_DIALOG(d)))),*client=gtk_spin_button_new_with_range(0,MAX_CLIENTS-1,1),*amount[MAX_RESOURCES];grid_row(g,0,"Client ID:",client);for(int r=0;r<MAX_RESOURCES;r++){amount[r]=gtk_spin_button_new_with_range(0,100000,1);char label[32];snprintf(label,sizeof label,"R%d amount:",r);grid_row(g,r+1,label,amount[r]);}gtk_widget_show_all(d);if(gtk_dialog_run(GTK_DIALOG(d))==GTK_RESPONSE_OK){int c=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(client)),req[MAX_RESOURCES];for(int r=0;r<MAX_RESOURCES;r++)req[r]=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(amount[r]));clear_text_output(app.banker_output_buffer);append_text_output(app.banker_output_buffer,request_resources(&app.banker_system,c,req)?"Request granted.":"Request denied: it exceeds the max claim, availability, or safe state.");append_text_output(app.banker_output_buffer,get_banker_state_string(&app.banker_system));}gtk_widget_destroy(d);}
static GtkWidget *create_banker_tab(void){GtkWidget *box=gtk_box_new(GTK_ORIENTATION_VERTICAL,8),*c=gtk_box_new(GTK_ORIENTATION_HORIZONTAL,8),*init=gtk_button_new_with_label("Initialize Resources"),*req=gtk_button_new_with_label("Request Resources"),*safe=gtk_button_new_with_label("Check Safety");gtk_container_set_border_width(GTK_CONTAINER(box),10);g_signal_connect(init,"clicked",G_CALLBACK(on_init_banker),NULL);g_signal_connect(req,"clicked",G_CALLBACK(on_banker_request),NULL);g_signal_connect(safe,"clicked",G_CALLBACK(on_banker_request),NULL);gtk_box_pack_start(GTK_BOX(c),init,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(c),req,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(box),c,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(box),output_view(&app.banker_output_buffer),TRUE,TRUE,0);return box;}

static void on_init_memory(GtkButton *b,gpointer u){(void)b;(void)u;GtkWidget *d=dialog_grid("Initialize Storage"),*g=gtk_bin_get_child(GTK_BIN(gtk_dialog_get_content_area(GTK_DIALOG(d)))),*count=gtk_spin_button_new_with_range(1,MAX_BLOCKS,1);grid_row(g,0,"Number of blocks:",count);gtk_widget_show_all(d);if(gtk_dialog_run(GTK_DIALOG(d))==GTK_RESPONSE_OK){app.num_blocks=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(count));gtk_widget_destroy(d);d=dialog_grid("Set Block Sizes (KB)");g=gtk_bin_get_child(GTK_BIN(gtk_dialog_get_content_area(GTK_DIALOG(d))));GtkWidget *sizes[MAX_BLOCKS];for(int i=0;i<app.num_blocks;i++){sizes[i]=gtk_spin_button_new_with_range(1,100000,1);char label[32];snprintf(label,sizeof label,"Block %d size:",i);grid_row(g,i,label,sizes[i]);}gtk_widget_show_all(d);if(gtk_dialog_run(GTK_DIALOG(d))==GTK_RESPONSE_OK){init_memory(app.storage_blocks,app.num_blocks);for(int i=0;i<app.num_blocks;i++)app.storage_blocks[i].size=gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(sizes[i]));refresh_memory();clear_text_output(app.storage_output_buffer);append_text_output(app.storage_output_buffer,"Storage initialized.");} }gtk_widget_destroy(d);}
static void on_allocate_memory(GtkButton *b,gpointer u){(void)b;(void)u;if(!app.num_blocks){append_text_output(app.storage_output_buffer,"Initialize storage first.");return;}GtkWidget *d=dialog_grid("Allocate Storage"),*g=gtk_bin_get_child(GTK_BIN(gtk_dialog_get_content_area(GTK_DIALOG(d)))),*name=gtk_entry_new(),*size=gtk_spin_button_new_with_range(1,100000,1),*strategy=gtk_combo_box_text_new();gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(strategy),"First Fit");gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(strategy),"Best Fit");gtk_combo_box_text_append_text(GTK_COMBO_BOX_TEXT(strategy),"Worst Fit");gtk_combo_box_set_active(GTK_COMBO_BOX(strategy),0);grid_row(g,0,"Job name:",name);grid_row(g,1,"Size KB:",size);grid_row(g,2,"Strategy:",strategy);gtk_widget_show_all(d);if(gtk_dialog_run(GTK_DIALOG(d))==GTK_RESPONSE_OK){const char *n=gtk_entry_get_text(GTK_ENTRY(name));clear_text_output(app.storage_output_buffer);if(!n[0])append_text_output(app.storage_output_buffer,"Allocation error: job name is required.");else if(memory_name_exists(n))append_text_output(app.storage_output_buffer,"Allocation error: that job already owns a memory block.");else append_text_output(app.storage_output_buffer,allocate_memory(app.storage_blocks,app.num_blocks,gtk_spin_button_get_value_as_int(GTK_SPIN_BUTTON(size)),n,(AllocationStrategy)gtk_combo_box_get_active(GTK_COMBO_BOX(strategy)))?"Memory allocated.":"Allocation failed: no suitable free block.");refresh_memory();append_text_output(app.storage_output_buffer,get_memory_state_string(app.storage_blocks,app.num_blocks));}gtk_widget_destroy(d);}
static GtkWidget *create_storage_tab(void){GtkWidget *box=gtk_box_new(GTK_ORIENTATION_VERTICAL,8),*view;gtk_container_set_border_width(GTK_CONTAINER(box),10);app.storage_list_store=gtk_list_store_new(4,G_TYPE_INT,G_TYPE_INT,G_TYPE_STRING,G_TYPE_STRING);view=gtk_tree_view_new_with_model(GTK_TREE_MODEL(app.storage_list_store));const char *cols[]={"Block","Size (KB)","Status","Job"};for(int i=0;i<4;i++)add_column(view,cols[i],i);GtkWidget *s=gtk_scrolled_window_new(NULL,NULL);gtk_container_add(GTK_CONTAINER(s),view);gtk_widget_set_vexpand(s,TRUE);gtk_box_pack_start(GTK_BOX(box),s,TRUE,TRUE,0);GtkWidget *c=gtk_box_new(GTK_ORIENTATION_HORIZONTAL,8),*init=gtk_button_new_with_label("Initialize Storage"),*alloc=gtk_button_new_with_label("Allocate Storage");g_signal_connect(init,"clicked",G_CALLBACK(on_init_memory),NULL);g_signal_connect(alloc,"clicked",G_CALLBACK(on_allocate_memory),NULL);gtk_box_pack_start(GTK_BOX(c),init,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(c),alloc,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(box),c,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(box),output_view(&app.storage_output_buffer),TRUE,TRUE,0);return box;}

static void on_refresh_dashboard(GtkButton *b,gpointer u){(void)b;(void)u;int allocated=0,total=0,free_kb=0,largest=0,fragmented=0,metrics=0;float wait=0,turn=0;for(int i=0;i<app.num_blocks;i++){total+=app.storage_blocks[i].size;if(app.storage_blocks[i].is_allocated)allocated+=app.storage_blocks[i].size;else{free_kb+=app.storage_blocks[i].size;if(app.storage_blocks[i].size>largest)largest=app.storage_blocks[i].size;}}for(int j=0;j<app.jobs.count;j++)if(app.jobs.jobs[j].has_metrics){metrics++;wait+=app.jobs.jobs[j].waiting_time;turn+=app.jobs.jobs[j].turnaround_time;}for(int j=0;j<app.jobs.count;j++)if(app.jobs.jobs[j].status==JOB_DENIED&&app.jobs.jobs[j].memory_size<=free_kb&&app.jobs.jobs[j].memory_size>largest){fragmented=1;break;}char report[512];snprintf(report,sizeof report,"Jobs submitted: %d\nGranted: %d | Denied/queued: %d\nAverage waiting time: %.2f\nAverage turnaround time: %.2f\nMemory utilization: %.2f%% (%d / %d KB)\nFragmentation blocking a request: %s",app.jobs.count,app.jobs.granted_count,app.jobs.denied_count,metrics?wait/metrics:0,metrics?turn/metrics:0,total?100.0*allocated/total:0,allocated,total,fragmented?"YES":"No");clear_text_output(app.dashboard_output_buffer);append_text_output(app.dashboard_output_buffer,report);}
static GtkWidget *create_dashboard_tab(void){GtkWidget *box=gtk_box_new(GTK_ORIENTATION_VERTICAL,8),*refresh=gtk_button_new_with_label("Refresh Report");gtk_container_set_border_width(GTK_CONTAINER(box),10);g_signal_connect(refresh,"clicked",G_CALLBACK(on_refresh_dashboard),NULL);gtk_box_pack_start(GTK_BOX(box),refresh,FALSE,FALSE,0);gtk_box_pack_start(GTK_BOX(box),output_view(&app.dashboard_output_buffer),TRUE,TRUE,0);return box;}

void gui_init(int argc,char *argv[]){gtk_init(&argc,&argv);job_manager_init(&app.jobs);app.window=gtk_window_new(GTK_WINDOW_TOPLEVEL);gtk_window_set_title(GTK_WINDOW(app.window),"Cloud Resource Allocation Simulator");gtk_window_set_default_size(GTK_WINDOW(app.window),1050,750);g_signal_connect(app.window,"destroy",G_CALLBACK(gtk_main_quit),NULL);GtkWidget *tabs=gtk_notebook_new();gtk_notebook_append_page(GTK_NOTEBOOK(tabs),create_scheduling_tab(),gtk_label_new("CPU Scheduling"));gtk_notebook_append_page(GTK_NOTEBOOK(tabs),create_banker_tab(),gtk_label_new("Banker's Algorithm"));gtk_notebook_append_page(GTK_NOTEBOOK(tabs),create_storage_tab(),gtk_label_new("Storage Management"));gtk_notebook_append_page(GTK_NOTEBOOK(tabs),create_dashboard_tab(),gtk_label_new("Dashboard"));gtk_container_add(GTK_CONTAINER(app.window),tabs);gtk_widget_show_all(app.window);gtk_main();}
